create table public.complexities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  position integer not null,
  color text not null default '#388bfd',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint complexities_name_not_blank check (btrim(name) <> ''),
  constraint complexities_position_positive check (position > 0),
  constraint complexities_position_unique unique (position),
  constraint complexities_color_hex check (color ~ '^#[0-9a-fA-F]{6}$')
);

create trigger complexities_set_updated_at
before update on public.complexities
for each row execute function public.set_updated_at();

alter table public.complexities enable row level security;

create table public.ad_statuses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  position integer not null,
  color text not null default '#388bfd',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ad_statuses_name_not_blank check (btrim(name) <> ''),
  constraint ad_statuses_position_positive check (position > 0),
  constraint ad_statuses_position_unique unique (position),
  constraint ad_statuses_color_hex check (color ~ '^#[0-9a-fA-F]{6}$')
);

create trigger ad_statuses_set_updated_at
before update on public.ad_statuses
for each row execute function public.set_updated_at();

alter table public.ad_statuses enable row level security;

alter table public.clients
  add column complexity_id bigint references public.complexities(id) on delete set null,
  add column ad_status_id bigint references public.ad_statuses(id) on delete set null,
  add column meli_user text,
  add column meeting_day smallint,
  add column meeting_time time,
  add column meeting_frequency smallint,
  add constraint clients_meli_user_not_blank check (meli_user is null or btrim(meli_user) <> ''),
  add constraint clients_meeting_day_valid check (meeting_day is null or meeting_day between 0 and 6),
  add constraint clients_meeting_frequency_valid check (meeting_frequency is null or meeting_frequency in (7, 15));

create index clients_complexity_id_idx on public.clients (complexity_id) where complexity_id is not null;
create index clients_ad_status_id_idx on public.clients (ad_status_id) where ad_status_id is not null;

insert into public.complexities (name, color, position) values
  ('Baja', '#3fb950', 1),
  ('Media', '#d29922', 2),
  ('Alta', '#f85149', 3);

insert into public.ad_statuses (name, color, position) values
  ('SI', '#3fb950', 1),
  ('NO', '#f85149', 2),
  ('Solo control', '#d29922', 3);
